services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.4
    container_name: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      - moodle-network  # Attach to the custom network

  moodle:
    image: docker.io/bitnami/moodle:4.5
    container_name: moodle
    ports:
      - '8081:8080'  # Expose port 8081 to host
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
    networks:
      - moodle-network  # Attach to the custom network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"  # Expose port 8080 to localhost
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Custom Nginx config
      - ./static:/usr/share/nginx/html  # Mount local ./static directory to Nginx's HTML root
    depends_on:
      - moodle
      - mariadb
    networks:
      - moodle-network  # Attach to the custom network

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local

networks:
  moodle-network:  # Define the custom network
    name: moodle-network
    driver: bridge  # Use the bridge driver (default driver)
