version: '3.8'
services:
  moodle:
    image: moodle:latest
    ports:
      - "8080:80"
    volumes:
      - ./moodledata:/var/www/moodledata
  moodle-db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=moodlepass