services:
  view-app:
    image: view-app:3
    hostname: view-app
    container_name: view-app
    ports:
      - 8080:5000
#    networks:
#      - app

  mongodb:
    image: mongo:latest
    hostname: mongodb
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: app
      MONGO_INITDB_ROOT_PASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://app:secret@mongo_db:27017
      ME_CONFIG_BASICAUTH: false
#    networks:
#      - app

  mongo-setup:
    image: mongo:latest
    hostname: mongo-setup
    container_name: mongo-setup
    links:
      - mongodb
    volumes:
      - ./mongodb:/mongodb
    command:
      - /mongodb/mongo_setup.sh

  redis-cache:
    image: redis:latest
    hostname: redis-cache
    container_name: redis-cache
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command:
      - redis-server
#    networks:
#      - app

#networks:
#  app:
#    external: true