services:
  static:
    image: nginx:latest
    container_name: static
    ports:
      - "8080:80"  # Expose port 80 on localhost
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Custom Nginx config
      - ./static/data:/usr/share/nginx/html  # Mount local ./static directory to Nginx's HTML root
